Repository milieuinfo/webcomponent-vl-ui-accordion, pull requests merged in 2020-02, with the labels that each got.

#74 Migratie naar nieuwe ES6 opzet
  demo/vl-accordion.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/style.scss
  src/vl-accordion.src.js
  test/docker-compose.yml
  test/e2e/accordion.test.js
  test/e2e/components/vl-accordion.js
  test/e2e/pages/vl-accordion.page.js
  test/unit/vl-accordion.test.html
  vl-accordion.js
Labels: chore

#75 Stijl import vervangen door inhoud, probleem met absolute paden
  package-lock.json
  package.json
  src/vl-accordion.src.js
Labels: bug

#77 Update dependency vl-ui-core to v4
  package.json
Labels: dependencies

#79 E2E flakiness
  package-lock.json
  package.json
  test/e2e/accordion.test.js
  test/e2e/components/vl-accordion.js
  test/e2e/pages/vl-accordion.page.js
Labels: chore
