Repository milieuinfo/webcomponent-vl-ui-accordion, pull requests merged in 2020-01, with the labels that each got.

#64 Update vl-ui-util
  .vscode/launch.json
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#65 UIG-289
  .gitignore
  .mocharc.js
  demo/vl-accordion.html
  index.js
  package-lock.json
  package.json
  test/e2e/accordion.test.js
  test/e2e/components/vl-accordion.js
  test/e2e/pages/vl-accordion.page.js
  test/unit/vl-accordion.test.html
  test/wct.docker.conf.json
  vl-accordion.src.js
Labels: chore

#66 Update naar laatste util
  package-lock.json
  package.json
Labels: bugfix

#68 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#69 Fix pad naar accordion in dist-folder
  vl-accordion.src.js
Labels: chore

#70 Update package-lock
  package-lock.json
  style.css
  test/docker-compose.yml
Labels: bugfix

#71 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: maintenance

#72 Update package-lock
  package-lock.json
  package.json
Labels: bugfix

#73 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance
